export interface InvoiceItem {
  id: number;
  item_id: number | null;
  item_code?: string;
  item_name?: string;
  qty: number;
  weight: number;
  g_weight: number;
  karat: string;
  price: number;
  price_w: number;
  item_disc_amt: number;
  note: string;
  trans_type?: number;
  G875?: string;
  total?: number;
  total_w?: number;
  total_a?: number;
  inv_note?: string;
  tax?: number;
  tax_prc?: number;
  stones?: string;
  item_disc_prc?: number;
  sn?: string;
  item_desc?: string;
  cr_date?: string;
  cr_user?: string;
  upd_date?: string;
  upd_user?: string;
  com?: number;
  inv?: number;
  item?: number;
}
